python3 src/learn_hnet.py \
    --experiment-name="nmb_test_0" \
    --num-image-encoders=6 \
    --encoder-batch-size=6 \
    --hnet-cond-emb-dim=32 \
    --cond-type="features" \
    --num-epochs=10 \
    --learning-rate=3e-3 \
    --batch-size=256 \
    --scheduler="off" \
    --warmup-steps=100 \
    --emb-loss=False \
    --normalize-output=True \
    --chunk-dim=256 \
    --hnet-decoder-type="mlp";