python3 src/learn_hnet.py \
    --experiment-name="ie_12-4_mlp_c-32_norm_inproj" \
    --num-image-encoders=12 \
    --encoder-batch-size=4 \
    --hnet-cond-emb-dim=32 \
    --cond-type="features" \
    --num-epochs=1 \
    --learning-rate=1e-2 \
    --batch-size=512 \
    --scheduler="off" \
    --warmup-steps=100 \
    --emb-loss=False \
    --normalize-output=True \
    --chunk-dim=256 \
    --hnet-decoder-type="mlp";
